baseURL = "https://ajsmith.co"
languageCode = "en-us"
title = "a j smith"

publishDir = "docs" 
enableGitInfo = true
footnoteReturnLinkContents = "↩"
lastmod = [":fileModTime", ":default"] # auto populates lastmod date

[taxonomies]
  tag = "tags"

[params]
  ImageMaxWidth = "800"
  analyticsid = ""
  additionalmetatags = "<meta name=\"msvalidate.01\" content=\"\" />" 
  humanDateFormat = "Monday 02 Jan 2006"
  contactformEndpoint = "https://submit-form.com/TMzsthUG"
  contactformAdditionalCode= "<input type=\"hidden\" name=\"_redirect\" value=\"https://ajsmith.co/thankyou\"/>"
  botpoisonPublicKey = "pk_ceb1f068-0be7-467b-b9c5-3c722f2d4627" 
# another possible color scheme: 493829/eb8f0c
# also see internalpointers.com

# theming and reusable code
[module]
  [[module.imports]]
    path = "github.com/ajs17/hugo-min-components"
 
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
